Applied-GeoSolutions/gips

README.md, install.sh
So this uses `pip` and `virtualenv` instead of `setup.py develop` etc, but I figure any install method that is correct is better than none.  Also it does some safety checks when it runs and stops on error immediately (thanks to `set -e`).
The various `gips_*` executables run successfully after I used this install script on my own machine, but there could still be problems; I figure I can iterate as I go if I discover something's wrong/missing.
=> Installation script for gips & edit for README

conftest.py, gips/data/core.py, gips/data/landsat/landsat.py, gips/test/landsat.sh, gips/test/sys/expected/landsat.py, gips/test/sys/expected/repo_src_alteration.py, gips/test/sys/t_landsat.py, gips/test/sys/t_modis.py, gips/test/sys/t_repo_src_alteration.py, gips/test/sys/util.py, gips/test/unit/t_landsat.py
* Improvement to system test harness:  optionally ignore stderr emitted by programs under test
* Fix #61, which is related to hyphens in the name of directories in the GIPS data repo.
* For #61, first-ever unit tests for GIPS!  :tada: 
* System tests for landsat, which are similar to modis, including expectations file in `expected/landsat.py` and tests in `t_landsat.py`.  Inventory-fetch is tested in the same files as modis (they have more in common than not).  This maybe fixes #46 because there's comprehensive coverage (based on `landsat.sh`) but no atmo correction and not super-good performance.
Speaking of performance, I have a branch with a nascent caching system, but it's not quite ready and I don't like my branches to live too long.
=> fix #61, fix(?) #46, improve system test harness

dev_requirements.txt, gips/data/modis/modis.py, gips/test/unit/t_modis.py, gips/test/unit/t_modis_fetch.py, requirements.txt
This is a fix for #63.
Replace urllib2 with requests for http fetches, but it doesn't support ftp so continue to use urllib2 for that.  A new constant in `modisAsset` tells which asset data need auth.  Auth creds are taken from settings; unfortunately there's no way around storing them in plaintext for the time being.
`modisAsset.fetch` is now covered by unit tests, which are complex becaues `fetch` does lots of I/O.
Note that the key system test which exercises `fetch()` passes right now:
```py.test --src-altering gips/test/sys/t_repo_src_alteration.py::t_modis_inv_fetch```
Many of the rest of the system tests fail due to an unrelated problem at the moment, but these should not be dependent on the fetch method.
=> 63 modis auth

gips/__init__.py, gips/test/unit/t_core.py
Fix for the testing problem induced by altering the version string:  GIPS puts its version number in files it generates as useful metadata for the files' provenance.  Now users can specify an appropriate override for the GIPS version to ensure tests pass.  Currently the right value for testing is:
`GIPS_OVERRIDE_VERSION='0.8.2'`
In the future the generated file checksums should be changed to match a permanent version string such as '0.0.0-dev' or something similar, which would then be a requisite for performing system tests, so that someday when GIPS' version string increments it'll be less confusing.
=> For convenient testing, overridable version string

gips/data/core.py, gips/data/modis/modis.py, gips/inventory.py, gips/parsers.py, gips/scripts/inventory.py, gips/test/sys/expected/modis.py, gips/test/sys/expected/repo_src_alteration.py, gips/test/unit/t_modis_fetch.py
This was made by:  `git checkout modis-6 && git rebase -i master HEAD --onto dev`
The diff doesn't look exactly the same as the old PR:
https://github.com/Applied-GeoSolutions/gips/pull/53
@bhbraswell could you read through this and confirm that it looks right?  If there are any problems we can add commits until it's okay.  Likewise I would like to add unit tests.  I also want to confirm system tests still pass, but for that I have to wait on other PRs.
=> Fix for #44, add support for modis collection 6 (and retain support for 5)

dev_requirements.txt, gips/test/sys/t_repo_src_alteration.py
Fix to test breakage on Wednesdays, but not a fix for accompanying UX issues in gips itself.
=> 57 sys test updates to handle issue

gips/data/modis/modis.py, gips/test/unit/t_modis_asset.py
Fix for this issue:
https://github.com/Applied-GeoSolutions/gips/issues/79
Does it by unifying the way file globs are treated.
Most of the time required to fix this was taken up by writing the test, but all the asset types are covered by it, so hurray!
=> fix for issue 79, ruggedizes asset globs

gips/algorithm.py, gips/atmosphere.py, gips/core.py, gips/data/aod/aod.py, gips/data/core.py, gips/data/landsat/landsat.py, gips/data/merra/merra.py, gips/data/merra/raster.py, gips/data/modis/modis.py, gips/data/prism/prism.py, gips/data/sarannual/sarannual.py, gips/data/weld/weld.py, gips/inventory/__init__.py, gips/inventory/orm/__init__.py, gips/parsers.py, gips/scripts/archive.py, gips/scripts/config.py, gips/scripts/info.py, gips/scripts/inventory.py, gips/scripts/mask.py, gips/scripts/process.py, gips/scripts/project.py, gips/scripts/stats.py, gips/scripts/tiles.py, gips/test/unit/t_core.py, gips/test/unit/t_utils.py, gips/tiles.py, gips/user_settings_template.py, gips/utils.py
Two-mode error-handling for GIPS; fix for issue #8.  One mode lets GIPS behave well as a library; mostly on error it reports to stderr then re-raises properly.  The other mode lets GIPS play nice as part of a CLI application, in that it doesn't report tracebacks unless verbosity is high.  Both modes support optional 'continuable' errors, which lets GIPS keep working after some errors, if the user permits.  The new error handler looks like this in situ:  `with utils.error_handler('Bad date specification'):`
Walking the code one will see this stuff:
* New error handling implemented in `gips.utils`, along with backing code for setup & config; unit tests also
* GIPSParser changed to have consistent and (now) necessary command-line options for all gips programs.
* Critical and problematic …
=> 8 error handling

gips/data/core.py, gips/data/modis/modis.py, gips/datahandler/__init__.py, gips/datahandler/api.py, gips/datahandler/torque.py, gips/datahandler/worker.py, gips/inventory/dbinv/api.py, gips/inventory/dbinv/models.py, gips/test/int/t_datahandler.py, gips/utils.py
This can either merge into the batch-scheduler branch or can sit here to grow more commits as I work on the prototype.  Now that I have something to schedule (fetch), I'm stepping up one level to the job submitter.
big items:
* scaffolding & stubs for the scheduler, mostly under datahandler/
* single-asset fetching function, currently works with modis:
gips.datahandler.worker.fetch
* draft of pure python torque work submitter
small items mostly to support big stuff:
* adapt dbinv.api to use asset status more conveniently
* change modisAsset.fetch to return list of retrieved filenames
* hack lib_herror_handler so it doesn't neglect the error prefix string
* integration test:  calls fetch() programmatically but actually fetches an
asset from modis servers
=> proto: datahandler scaffolding & working fetch()

gips/datahandler/torque.py, gips/datahandler/worker.py
Note that I tested it with a quick and dirty script and observed the
torque job build the product files in the output dir.  Also removed some
increasingly pointless gatekeeping per advice from a colleague.
=> quick PR to integrate export into worker functions

gips/scripts/archive.py, gips/scripts/mask.py
For some reason these commands were never caught up to the change to the way the default parser was added.
=> fix broken argument parsing for mask & archive

gips/datahandler/worker.py, gips/scripts/spatial_wrapper.py
This PR hooks up the _aggregate function for export_and_aggregate. Currently it just calls one of the methods of spatial_wrapper. Spatial_wrapper was written to be a command line application but isn't being used that way, so changes should probably be made here.
_aggregate requires a Job and an export/project directory as inputs.
Job:
`{u'id': 1,
'site': u'banana',
'spatial': u"{'site': ['h12v04']}",
'status': u'requested',
'temporal': u"{'dates': '2012-336,2012-338'}",
'variable': 11}`
Variable 11 points to `modis_indices_evi` in my DB.
To get an export directory:
`﻿⁠⁠⁠⁠py.test -s -vv -k 't_export_helper'`
_aggregate should produce 3 Result objects.
Tests are currently being written.
=> _aggregate function changes

requirements.txt, setup.py
`matplotlib==2.0` requires `six==1.10`, so these requirements are tweaked in gips (and my landsat-util fork) to be `six>=1.9`.  This makes it such that there is not a version conflict for gips install.  I have tested that gips now installs happily in a fresh container.
=> relax six requirement

conftest.py, gips/test/README.md, gips/test/sys/expected/modis.py, gips/test/sys/util.py
Here's what it looks like in situ:
```(.venv) laptop2:~/src/gips$ time pytest --sys -s --ll debug --expectation-format -k 'modis and info'
DEBUG    conftest.py:66: value detected for data-repo: /home/tolson/src/gips/data-root
===== test session starts =====
platform linux2 -- Python 2.7.12, pytest-3.0.4, py-1.4.31, pluggy-0.4.0
Django settings: gips.inventory.orm.settings (from ini file)
rootdir: /home/tolson/src/gips, inifile: pytest.ini
plugins: mock-1.4.0, django-3.1.1, timeout-1.2.0, cov-2.4.0
collected 136 items 
gips/test/sys/t_modis.py DEBUG    util.py:50: command line: `gips_info modis`
DEBUG    util.py:55: standard output: GIPS Data Repositories (v0.8.2)
Modis Products v1.0.0
Terra 8-day Products
ndvi8       Normalized Difference Vegetation Index: 250m
temp8td     Surface …
```
=> Expectations format option for system tests

gips/test/unit/t_utils.py, gips/utils.py
Apparently I'm batting 1.000 this week: I missed two tests for remove_files that broke with the recent merge; this fixes them.
PS - Accidently made this PR against gipit/gips just now; closed it and opened this one.
=> fix broken unit tests for remove_files

gips/datahandler/api.py, gips/datahandler/queue/queue.py, gips/datahandler/queue/rq.py, gips/datahandler/scheduler.py, gips/datahandler/worker.py, gips/inventory/dbinv/models.py
Semantic changes:
* rewrites to the scheduler to avoid race conditions
* make `get_job_name` always emit ascii for compatibility with gippy deep in the call stack
* `chain=True` support for `rq.submit()`
* implement `rq.is_job_alive(job_id)`
* make `queue.submit` always emit full call signatures as the scheduler expects.  
Refactoring & minor changes:
* `processing_status` should be just changing indentation.
* move RQ setup code to separate function for common use
* revert silly logging optimization
* improve various comments.
My manual test process was to run this code, then manually step through by running the scheduler repeatedly.  I observed correct-looking in both torque and rq modes.  Job submission snippet is:
```
shp_full_path = '/home/tolson/src/gips/gips/test/NHseacoast.shp' …
```
=> 234 fetch, process, and E&A support in RQ for the datahandler

gips/inventory/dbinv/api.py
The previous update_or_create would use the whole row as the search key,
but try to set status='complete'.  If the row was already present but
with a different status, this would violate uniqueness constraints.  So,
specify unique-together fields as search key and update the rest of the
fields via `defaults`.
=> 239 fix 'requested' incompatibility

gips/data/daymet/daymet.py, gips/data/prism/prism.py, gips/inventory/orm/__init__.py, requirements.txt, setup.py
Daymet was busted 
1 - The URL changed; now uses https, also the format of the url is different
2 - Pydap 3.2 accesses data differently; added to requirements.
=> Remove merra from orm blacklist, fix tabs in prism, fix daymet asset url, update pydap version

gips/datahandler/scripts/geokitd.py, gips/parsers.py, gips/scripts/util.py, gips/scripts/zs.py, gips/utils.py
New command-line program, `gips_zs`, for calling the datahandler's API remotely:
```
$ gips_zs --help
GIPS Zonal Summary (v0.8.2)
usage: gips_zs submit [-h] [-v {0,1,2,3,4,5,6}] site_name data_spec site dates
positional arguments:
site_name             User-specified keyword or nickname; no computational
purpose
data_spec             Combination of driver, product, and band
site                  Define geographic boundaries for the summary
dates                 Range of dates (YYYY-MM-DD,YYYY-MM-DD)
optional arguments:
-h, --help            show this help message and exit
-v {0,1,2,3,4,5,6}, --verbose {0,1,2,3,4,5,6}
Verbosity - 0: quiet, 1: normal, 2+: debug
$ gips_zs status --help
GIPS Zonal Summary (v0.8.2)
usage: gips_zs status [-h] [-v {0,1,2,3,4,5,6}] job_id
positional arguments: …
```
=> 254 zonal summary command-line program

gips/data/modis/modis.py, gips/test/sys/t_modis.py
`return` is `return None` which makes `modisAsset.fetch` croak because it expects the output of `query_service` to be iterable.  Fixed by returning `[]`.  This in turn made the modis `--setup-repo` bit in the sys tests work without needing to wimp out about the exit status.
=> fix modis fetch TypeError

gips/datahandler/api.py, gips/datahandler/scheduler.py, gips/inventory/dbinv/models.py
Rewrite processing_status into status_counts, which reports on assets,
products, or both, at the caller's option.  Report both for get_status
but keep just-products for the use of the scheduler's
export-and-aggregate function.  Add valid status dict to models.py so
that get_status doesn't have to filter.
=> 127 add assets to datahandler.api.get_status:

gips/core.py, gips/datahandler/api.py
If assets exist for a product, the product isn't added to the database.
Fix this by moving product creation in the DB to its own loop, wherein
it looks up what assets are expected to be available.  Remove pointless
attribute from TemporalExtent.  Improve docstrings.
=> fix products error during query step:

gips/datahandler/scheduler.py
Fail jobs with failed assets or products.  Fail products that have failed asset dependencies.
I wanted to re-use the select-for-update bit for both finding products to fail and finding products to schedule, but alas, select-for-update is incompeatible with `distinct()`, which is needed to report accurately on how many products failed (due to join duplicating products in resulting queryset).
=> 286 failure tracking

install_datahandler.py, lxc.sh, setup.py
fixes #291 by as described in that issue.
also `lxc.sh` should now be usable as intended, the blocker to it running with a fresh container was that no commands can fail when you use `set -e`, and the `lxc info $CONT | grep $SNAP` was failing.  `set -e` is important for actually finding out that you had an error in a bash script, instead of it just marching on and failing all over the place in a confusing manner.
Could whoever reviews this please **NOT** merge, I'd like to change the `lxc.sh` defaults before merging.
=> services no longer missing

install_datahandler.py
Previous `install_datahandler` script used an implicit "Oh you're installing from a cloned repo, so developer mode." to enable development installs.  This switch will instead make it an explicit option .
=> make developer-install an explicit option

gips/data/core.py, gips/data/prism/prism.py, gips/test/int/t_core.py, gips/test/int/t_utils.py, gips/test/sys/expected/prism.py, gips/test/sys/t_prism.py, gips/test/sys/util.py
This is the first two steps of #304, which is to write a method for `gips.data.core.Data` to let Data instances create tempdirs for making products.
Minor changes include various linewrapping, docstring, and other nonsemantic improvements.
Important changes:
* `gips.data.core.Data.make_temp_proc_dir`, which is a trivial wrapper around `gips.utils.make_temp_dir`, and integration tests for both.
* Use the tempdir method for prism processing.
* Just enough improvements to prism & the system test harness to make it functional enough to pass sys test t_process before I started changing things.  This took a lot longer than the changes to `prismData.process()` actually.  On the upside we have a pattern for testing symlink products now.
PS - I decided to leave the refactoring of repeated code at …
=> #304 tempdir method & prism implementation

gips/data/core.py, gips/data/merra/merra.py, gips/data/modis/modis.py, gips/test/sys/expected/merra.py, gips/test/sys/expected/modis.py, gips/test/sys/t_merra.py, gips/test/sys/t_modis.py
Here's a decorator for making & destroying tempdirs & conversion of modis & merra to it.  sys test t_process passes.
Note the diff is a little strange around the modis landcover stanza; it thinks the if-statement got moved, when really things moved around it.
Doing this PR now, even though it's pretty short, so I can make sure the approach is acceptable before I rip through the rest of the drivers.
So github has breadcrumbs, this is for issue #304 even though it already says 304 all over the place.
=> #304 process decorator and some driver conversions

gips/data/daymet/daymet.py, gips/data/sentinel2/sentinel2.py, gips/data/weld/weld.py, gips/test/sys/expected/sentinel2.py
For issue #304 convert three more drivers.  Sentinel-2 needed more refactoring than the others as it had its own way to handle broken product files, so that had to be removed to make it match the common way.
=> convert sentinel2, daymet, and weld

gips/data/core.py, gips/data/landsat/landsat.py
Biggest change outside tempdir usage is refactoring indices processing to a separate method, similarly to Sentinel-2.  Notice the `zip(...)` calls are removed; this is intentional as iterating through two different dicts in parallel seemed risky to me.
Given larger changes to landsat I didn't run the system tests, but all the code that got changed also got exercised I believe, by:
```
gips_process landsat -v6 -p bi lswi-toa ref-toa ref ndvi-toa bi-toa ndvi evi-toa -t 012030 -d 2015-352
GIPS_ORM=false gips_process landsat -v6 -p ndvi8sr -t 121061 -d 2014-233
```
Reason for `GIPS_ORM=false` is #315
=> 304 landsat temp dir usage (except acolite)

conftest.py, gips/data/prism/prism.py
Fixes #305 by letting the larger context do the DB insert for the asset.  Note that `test.sys.t_prism.t_inventory` passes now, which remedies the observed problem that lead to #305.
=> fix 305: hook prism fetch into archive process

gips/data/prism/prism.py
Fix for #131 for prism.
URLs aren't actually used by ftplib so no need to parse them.  New
method ftp_connect for use by both query & fetch.  New method
query_provider in the pattern of PR #272.  query_provider & fetch
cooperate to share an ftp connection.  Substantial refactoring for
robustness and simplicity.
=> prism query/fetch bifurcation

gips/data/merra/merra.py
Asset fetch was busted for merra because it searches each line of the index listing, whicn includes random html and other characters.  This fixed it.
=> fix merra fetch; ^$ broke line match in query

gips/data/core.py, gips/data/prism/prism.py, gips/data/sentinel2/sentinel2.py
Now their `Data._products` should support minimum content for DataVariable insertion.
Might be reaching with the DRY-out in Sentinel-2; not too hard to get back the old format so just say the word.
=> Sentinel2 & prism DH metadata

gips/data/aod/aod.py, gips/data/cdl/cdl.py, gips/data/core.py, gips/data/daymet/daymet.py, gips/inventory/__init__.py, gips/inventory/dbinv/api.py, gips/inventory/orm/__init__.py, gips/test/unit/t_daymet.py
Fixes for #251 & #314; note this replaces PR #314; also the branch is based on latest dev, not the commit the previous PR was based on.  As usual, there's minor refactoring & stale/redundant comment cleanup here and there, and these bigger changes:
Sometimes assets have products built in to them (self.products). After fetch, add those products to the ORM.  New method `core.Asset.parse_asset_fp` that provides a common way to parse asset filenames.  `busted_drivers` loses daymet & CDL entries.
AOD got refactoring to use an existing dict instead of overwriting it; this makes debugging easier.
CDL & daymet both got their asset/product files renamed to match standard gips products.  This is to make various things work more smoothly, most notably product rectification.  Both got their assets …
=> 251 & 314 ORM & partial DH compatibility for two unusual drivers, daymet and CDL

gips/data/aod/aod.py, gips/data/core.py, gips/data/prism/prism.py
Fixes, I think, both #131 & #335.  Basically I mimicked prism, and refactored prism a little into common code besides.  Implemented query_provider for aod, and have aod use that for its fetch.  As such now there are no users of `Asset.fetch_ftp`, I don't think.  Deleting that method can be added to this PR if desired.
=> 131 335 refactor ftp & aod query/fetch

gips/data/core.py, gips/data/merra/merra.py, gips/data/modis/modis.py, gips/data/weld/weld.py, gips/test/unit/t_core.py, gips/test/unit/t_landsat.py, gips/test/unit/t_modis_fetch.py
New common feature is the Repository class method `managed_request`, which handles redirects and auth for earthdata.  This is called by modis & merra fetch.
Fix for #201 for modis, merra, & weld.  Confirmed no netrc file is necessary; both modis and merra system tests all pass, including the modis fetch test; unit tests made to pass with some difficulty.
This PR is based on a branch by @bhbraswell; see #201 for details.
=> 201 fix for modis, merra, and weld auth

gips/data/landsat/landsat.py, gips/test/sys/expected/landsat.py
quick addition of existing gippy.algorithms.Indices product.
Only change to current tests is that it shows up in `gips_info` output.
=> adding VARI to landsat

install.sh, setup.py
Tested with making a fresh venv, then activating it, then:
```
(.venv) tolsonlt:~/src/also-gips$ fmask_sentinel2makeAnglesImage.py # <-- imports rios
usage: fmask_sentinel2makeAnglesImage.py [-h] [-i INFILE] [-o OUTFILE]
optional arguments:
-h, --help            show this help message and exit
-i INFILE, --infile INFILE
Input sentinel-2 tile metafile
-o OUTFILE, --outfile OUTFILE
Output angles image file
```
For usgs I did `python -c 'import gips.data.landsat.landsat'`; before, ImportError and heartbreak :broken_heart: , after, joy and rainbows. :rainbow:
=> unbreak rios install & landsat's use of usgs

gips/data/landsat/landsat.py
Main issue was that nodata value wasn't set on `'cloudmask'`, but in addition to that, inverting the mask to be a `good_data=1`, `bad_data=0` simplifies usage.  Also, observed that the cloudmask seemed to miss hazy edges of clouds, so added an erosion step to label more data as `bad` and avoid the inclusion of polluted pixels.  fixes #380
=> fix for #380 PLUS add tempdir usage to fetch

gips/data/landsat/landsat.py
fixes #362 and fixes #257.  See #375 for the first attempt.  Note I didn't take the time to test-merge and attempt to populate the datavariable table; instead I ran gips_process on a large set of landsat products.
The diff is substantially larger for reasons that are mysterious to me; both cherry-pick and rebase --onto resulted in several extra lines per product, but the extra lines are all useful for the dev branch eventually anyway, so I left them in.
=> 362 257 band names, units, and other metadata for landsat products

gips/atmosphere.py, gips/data/landsat/landsat.py, gips/data/sentinel2/sentinel2.py, gips/test/sys/expected/landsat.py, gips/test/sys/expected/sentinel2.py, gips/test/sys/t_sentinel2.py
* moved the product dicts to gips.atmosphere to reduce boilerplate.
* two internal assumptions about landsat in the acolite processing function were turned into arguments, so s2 could call it in an s2 way
* it ran over time budget so I didn't add an acolite test for sentinel-2, can do that presently if it's needed
=> 392 acolite for s2

gips/data/core.py, gips/data/landsat/landsat.py, gips/data/merra/merra.py, gips/data/modis/modis.py, gips/data/prism/prism.py, gips/data/sar/sar.py, gips/data/sentinel2/sentinel2.py
Now drivers only need to set `self._version` to get the default version handling behavior.
Example for possible over-ride might be to consider `C1` and `DN` equivalent in the landsat driver.
=> fixes #85 and DRYs out versioning

gips/data/landsat/landsat.py
Second verse, same as the first:  This fixes #407 by using an explicit asset type for reading metadata and data.  Also removes redundant product dependency check.
=> Use an explicit asset type for reading metadata and data

gips/data/core.py, gips/data/landsat/landsat.py
This moves the landsat specific "check if tile is an int" functionality into the landsat driver.
=> Moving landsat-specific get_geometry code to landsat driver

gips/data/modis/modis.py, gips/data/sentinel2/sentinel2.py
This fixes #453 and fixes #439 by building off the work for #439.  Removes refl, deprecates indices, replaces the latter with individual products in a new 'Index' product group.
=> 453 & 439 add several indices as separate products to modis

gips/data/core.py, gips/data/prism/prism.py
(This includes commits from PR #475 because they were blockers.)
This fixes PRISM nuisance downloading #252 and an undocumented bug in versioning where the meanings of "early" and "provisional" were swapped.
=> 252 prism downloads too much
