- install.sh
this is for the user problem on Ubuntu 14.04
> Support git<2.0 and be more helpful with config

- install.sh
This is a try at merging into dev from a branch founded on master; it looks like it picked up the one unique commit so I think it may be safe to merge.
> generic-izing virtualenv install

- gips/version.py
The dev branch can't be 0.8.2 because that's already shipped
> establish dev version string

- README.md
- gips/test/README.md
I had some time while waiting on a PR to merge so I updated the testing README
> update testing readme to be more complete

- gips/data/prism/prism.py
- gips/test/sys/expected/prism.py
- gips/test/sys/t_prism.py
- setup.py
This fixes issue #76, and increases test coverage.
> 76 prism base product

- gips/data/prism/prism.py
trivial.  missed the Balmer peak.
> PRISM urls transposed

- gips/data/landsat/landsat.py
- gips/utils.py
> 41 landsat fetch

- gips/atmosphere.py
Begin (and maybe end) of addressing #100
> matplotlib config to drop X

- gips/settings_template.py
- install.sh
I was able to install GIPS on a fresh container but had to make a couple changes in install.sh for it to work. Also for convenience I think it is useful to have a placeholder in the setup template to show where the Earthdata authentication goes, e.g. for MODIS.
> small changes needed for installation to work properly

- gips/test/sys/expected/merra.py
- gips/test/sys/t_merra.py
Here's what I have; it's just one commit but it's a good start I believe.
Note that I made this branch some time ago so the existing tests may be stale.
Note this PR is targetting the auth branch.
> incomplete merra system tests -> merra_auth branch

- gips/datahandler/torque.py
- gips/datahandler/worker.py
- gips/inventory/dbinv/api.py
- gips/inventory/dbinv/migrations/0003_auto_20161212_2227.py
- gips/test/int/t_torque.py
- gips/utils.py
- requirements.txt
* Densest edits in `torque.py`.
* moved the grouper function from the dbinv api for general use in `gips.utils`.
* Wrote two integration tests:  One for a single asset fetch, and one for three fetches in two uneven batches.
* Fixed a very stupid bug in `worker.py`.
* Committed the help I got from @remeryAGS (see 545923f); this is to make postgis work properly.
> working function for submitting batches of fetch actions to torque

- gips/datahandler/worker.py
- gips/inventory/dbinv/api.py
- gips/inventory/dbinv/models.py
- gips/test/int/t_datahandler.py
Also includes:
* working integration test
* fixes for various small bugs elsewhere
> proto: Working process worker function

- gips/datahandler/geokit_api.py
> intial api

- gips/datahandler/worker.py
- gips/test/int/t_datahandler.py
Baldly stolen from `scripts/project.py`.
It takes an absurd pile of arguments as the integration test will show.
> worker function for export aka gips_project

- gips/data/modis/modis.py
- gips/datahandler/worker.py
When asset fetch fails, move to failed state.
Also, make fetch always return a list.
> Batsched fetch

- gips/datahandler/api.py
- gips/inventory/dbinv/models.py
exposed status strings in models.py
added processing status function
> processing_status for datahandler.api

- gips/datahandler/api.py
- gips/datahandler/scripts/scheduler.py
- gips/datahandler/torque.py
Just a little more meaningful output from the scheduler & the workers, mostly in terms of headers when they run.
> Scheduler UX sugar

- gips/datahandler/worker.py
- gips/test/unit/t_datahandler.py
I think the creation and destruction follows the patterns we talked about; let me know otherwise, still 1 day until the great holiday vanishing.
> finishing the gateway function export_and_aggregate

- gips/datahandler/api.py
- gips/datahandler/torque.py
- gips/datahandler/worker.py
- gips/inventory/dbinv/models.py
* fixes for processing_status (seems to work, not very well tested)
* scheduling of export and aggregate step (clunky, but seems acceptable for prototype)
* tracking of job status necessary for E&A steps (not tested all the way through)
* some minor cleanup
* bugfix for issue related to new additional printing (UX sugar) during processing
The arguments being passed to export and aggregate are not correct. Hoping that T&R can clean that up in the AM.
> scheduling of export and aggregate

- gips/data/landsat/landsat.py
- gips/test/sys/expected/modis.py
- gips/test/unit/t_utils.py
- gips/utils.py
I went after some high-priority stuff and easy stuff: Either stuff that mattered a lot (sees frequent use in the codebase) or things that are covered or could easily be covered by tests.  Note this is for issue #8
> 8 backfill - round of edits fixing error handling

- gips/datahandler/api.py
- gips/datahandler/geokit_api.py
- gips/datahandler/scripts/scheduler.py
- gips/datahandler/torque.py
- gips/datahandler/worker.py
- gips/inventory/dbinv/models.py
- gips/scripts/spatial_wrapper.py
- gips/test/int/t_datahandler.py
Export and aggregate are hooked up. Full path through the system is now possible. 
Added a few settings for torque:
TORQUE_QUEUE: specified as queue name, or queue name @ queue host
TORQUE_NODE: specify that a specific node should be used (hopefully this can be dropped eventually. currently useful if not all nodes are configured appropriately)
> export and aggregate

- gips/tiles.py
- gips/utils.py
> Quick and dirty fix for #179

- gips/data/modis/modis.py
quick fix for #181; existing system tests pass, unit tests pass, manual test of landcover product generation passed.
> 181 quick and dirty fix

- gips/data/modis/modis.py
> 70 delete objects to cover for GDAL<2 faults

- gips/test/unit/t_utils.py
- gips/utils.py
Two main changes:
* Add a conditional so a non-existent user settings file is passed over
* Remove continuable from the error hander
> fix for #189, noisy settings problem

- gips/data/modis/modis.py
- gips/version.py
this corresponds to the PR for `master`, with the conflicts already sorted out.  As I needed the gdal-hdf-subdataset fix on master, it shows up here again, but merges w/o issue.
> Hotfix ndvi8 to dev

- gips/data/modis/modis.py
- gips/version.py
issues fixed in dev that needed to go to master for use.
> Hotfix ndvi8 + gdal hdf:sds issue 

- gips/data/landsat/landsat.py
Due to changes in the response of the query for landsat assets, we needed to modify the fetch function.
> Landsat fetch fix

- gips/data/modis/modis.py
- gips/datahandler/api.py
- gips/datahandler/torque.py
- gips/datahandler/worker.py
- gips/inventory/dbinv/models.py
- gips/utils.py
quick PR as I pivot to RQ; e08a423 is the necessary fetch fix; 0def740 is trying to make life a little easier.
> fetch fix + smallish debugging improvements

- gips/datahandler/worker.py
- gips/test/int/t_datahandler.py
- gips/test/unit/t_datahandler.py
This is #174 but with an extra thing (which has since been removed).
A few tests had been broken by changes to calling conventions; this fixes that.
It used to have some error reporting fixes but that got removed since it wasn't clear what the best design would be.
> Export test fixes

- gips/datahandler/scheduler.py
simple file lock to prevent two `scheduler.py` from running at the same time
> lock to keep more than one scheduler running at a time

- gips/scripts/config.py
DataVariables shouldn't have to be purged and re-created
> changing DataVariable creation to allow updates

- gips/datahandler/Readme.md
just some basic info for RQ; not complete but fortunately neither is gips deployment generally.
> Add RQ info to DH Readme.md

- gips/data/modis/modis.py
- gips/test/sys/t_modis.py
- gips/test/unit/t_modis_fetch.py
All I did was:
```
$ git checkout batch-scheduler gips/data/modis/modis.py
$ git commit -av
$ # (fixed tests here)
```
Test procedure:
```
$ rm -rf data-root/               # clear local archive
$ gips_config env                 # set up new one
$ gips_inventory modis --rectify  # sync local sqlite DB
$ # first run the fetch test
$ time pytest --ll debug -s -x -vv --sys -k 'fetch and modis' --src-altering
$ # then run the other sys tests
$ time pytest --ll debug -s -x -vv --sys -k 'modis' --setup-repo
$ # confirm unit tests pass
$ pytest
```
Good news:  I tried a merge back to the batch-scheduler branch in my own git repo and it worked with no conflicts.
> Port BS modis to dev

- gips/data/core.py
If the file exists in the filesystem, but not in the DB inventory, that's a bad state that should only happen in very strange circumstances.  So, it's okay to raise an exception and give up provided the error message is sensible.
> 147 raise when asset found in FS unexpectedly

- gips/datahandler/worker.py
It looked like this could be made off the base batch-scheduler branch without conflict so I went with that, just in the interest of Getting On With It.
> 230 wrap api.query_service in exception handler

- gips/data/prism/prism.py
- gips/test/sys/expected/prism.py
> 307 pptsum set nodata

- gips/data/landsat/landsat.py
- gips/settings_template.py
- install.sh
- setup.py
Two things of note:
* I put 12 days as the C1 latency, which is how long it takes for T1 and T2 data to become available. However, real time data is available, well, immediately. I figured that isn't suitable for most people, but thought it should be noted that the latency is technically 0.
* Since DN and SR assets aren't fetchable at all, I put the latency at infinity. Is there another case where the datahandler is exposed to non fetchable assets? Is the better way to specify this?
> Landsat dh compatibility

- gips/algorithm.py
- gips/atmosphere.py
- gips/data/aod/aod.py
- gips/data/core.py
- gips/data/landsat/landsat.py
- gips/data/prism/prism.py
- gips/data/sarannual/sarannual.py
- gips/data/weld/weld.py
- gips/scripts/archive.py
- gips/scripts/config.py
- gips/scripts/mask.py
- gips/test/unit/t_core.py
- gips/user_settings_template.py
- gips/utils.py
The rest of the items marked for fixing from #8 have been fixed; this PR now resolves #8, hopefully.
In some cases I second-guessed my original comment about what to do; some cases seemed not to warrant error-handling at all, for instance if the code is known to be inside another error handler already.  A few cases seemed to dissolve with refactoring, too.  Also decided to patch in the thing from #201 for weld.
I believe I've executed all this code, even the thing in algorithm.py by importing and calling main() directly.
> issue 8 backfill part 2 of 2

- gips/data/core.py
- gips/data/landsat/landsat.py
- gips/data/prism/prism.py
- gips/data/sentinel2/sentinel2.py
- gips/datahandler/api.py
- gips/datahandler/worker.py
- gips/inventory/__init__.py
- gips/inventory/dbinv/api.py
- gips/inventory/dbinv/models.py
- gips/scripts/zs.py
- gips/test/int/t_torque.py
- gips/utils.py
NOTE This branch is based on merge-dev-into-dh branch (see PR #329) and not the datahandler branch directly.  It can either merge into merge-dev-into-dh or else merge into datahandler after PR #329 merges.
This PR provides a basic ability to use gips_zs / the DH with CDL, prism, and sentinel2.  Not everything is supported, as for instance pptsum and most of sentinel2's products are incompatible with the DH right now.  Instead, you get the datavariable items `cdl_cdl_cdl`, `prism_tmax_tmax`, and similarly tmin and ppt, and a sorta hacked-in ref-toa workalike for sentinel2 which you can ask for with eg `sentinel2_reftoa_RED`.
Important changes to common code:
* Wrapped DH's worker.process function in a try-except so processing fails when it raises an exception.
* In dbinv.api, …
> basic support for prism, sentinel2, and CDL in the datahandler

- gips/data/core.py
- gips/test/int/data/README.md
- gips/test/int/data/africa-daily-chirps-v2.0.1997.07.01.tif.gz
- gips/test/int/t_chirps.py
- gips/test/unit/t_chirps.py
A few unit tests, an integration test too.  I needed less mocking than I'd feared once I realized I'd have to do cleanup anyway after the symlink got made.
> 342 chirps automated tests

- gips/data/landsat/landsat.py
small changes elsewhere for correctness & user experience
> 341 add cloudmask C1 landsat product, and:

- gips/data/chirps/chirps.py
> fix for #359

- gips/test/unit/t_modis_fetch.py
looks like they broke during the managed_request changeover; not sure what happened because it looks like there was some effort to integrate managed_request into the tests.  They're fixed now in any case.
> fix modis fetch unit tests

- gips/data/sentinel2/sentinel2.py
addendum to issue #370 that just cleans up a smidge.
> 370 s2 tile list

- gips/data/landsat/landsat.py
Not sure how it ended up with the wrong band name grab,  but this fixes it.
> fix busted cloudmask

- gips/data/landsat/landsat.py
this fixes #380 for real.  Problems manifested when mosaicking two tiles together and the nodata value was not being set in the border outside the scene.
> border fill was getting dropped

- gips/data/core.py
- gips/data/sar/sar.py
- gips/parsers.py
- setup.py
Fixes  #405.  And ALSO lso with your purchase:
1. error handling improvement
2. fix parser bug I recently introduced
3. updated gippy requirement (which only feels mostly silly)
> Palsar mask fix

- gips/scripts/config.py
- setup.py
fixes bug @bhbraswell found this weekend.  Good catch.
Also pip whines too much about http.
> Fix gips config env bug

- setup.py
Just one line -- gets the right gippy I guess.
> get the right gippy

- gips/core.py
- gips/parsers.py
- gips/scripts/inventory.py
- gips/scripts/process.py
- gips/scripts/project.py
- gips/scripts/tiles.py
- gips/test/int/t_raster_spatialspec.py
- gips/test/sys/expected/modis.py
- gips/test/sys/t_modis.py
- gips/tiles.py
- gips/utils.py
this changes the files required by system tests, so the artifact tarball should be updated
> 388 spatialextent from raster

- gips/data/core.py
- gips/data/landsat/input_file_tmp.inp
- gips/data/landsat/landsat.py
- gips/data/landsat/lndortho.cps_par.ini
- gips/data/sentinel2/sentinel2.py
> Landsat coreg product

- gips/data/sentinel2/sentinel2.py
Fix for #433; everything looks nice in qgis & `gdalinfo -stats` but I'm not confident that I understand the math changes I made, so here's a path to products produced with this branch:
`/scratch/tolson/pub/433-final-sample-products`
> 433 sentinel2 gain

- gips/data/landsat/landsat.py
quick fix for the USGS fields being renumbered.  Longer term fix is to programatically determine those at runtime.  Maybe memoize them daily or something.
> USGS dataset fields renumbered

- gips/data/landsat/landsat.py
- gips/test/sys/expected/repo_src_alteration.py
- gips/test/sys/t_landsat.py
- gips/test/sys/t_repo_src_alteration.py
Thought I had tested that last PR w/o needing credentials, but it turns out that they are just cached somewhere
... so let's cache too!
> usgs.dataset_fields needs creds too

- gips/data/core.py
This handles the case of duplicate assets of differing versions by keeping the greatest versioned asset and pitching the others.  I suppose that we could ignore the others and just return the file path for the latest and greatest, but I'm not feeling hoarder at the moment.
> handle duplicate assets (of differing versions)
